### ISSUE TITLE
Error re-deploying network layer caused trying to destroy existent s3 bucket

### ISSUE THREAD

**Issue by mvago-flx** [binbashar/terraform-aws-vpc-flowlogs#13]
## Describe the Bug
When we try to re-apply the network layer, fails on creating s3 bucket. The s3 bucket already exists

## Expected Behavior
Delete or reuse existent bucket

## Steps to Reproduce
1. Go to '...' network layer on terraform-aws-vpc-flowlogs
2. Run '....' leverage run init & leverage run apply
3. Enter '....'
![image](https://user-images.githubusercontent.com/102180756/181826370-70e68b65-33f5-4f52-9d90-925f04c5e38d.png)

## Environment (please complete the following information):
leverage, version 1.7.2

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

## Additional Context
Possible solutions
1- hacer q al bucket name lo obtenga desde el modulo q lo crea; de ese modo TF se daria cuenta q primero tiene q aplicar el modulo q crea el bucket y luego cualquier otro recurso q use el bucket
2- usar depends_on, como dijo Exe, para indicarle explicitamente a TF q tiene q respetar un orden de creacion

**Comment by exequielrafaela** [comment]
@lgallard let's consider what we've discussed with @diego-ojeda-binbash and @mvago-flx to fix this:

- Add support to enforceSSL policy
- Add support to deactivate the default policy
- Add support to add extra policies to be merged with the one configurable through the module

Consider S3 terraform module as reference => https://github.com/binbashar/terraform-aws-s3-bucket

**Comment by exequielrafaela** [comment]
@mvago-flx thanks for reporting this issue and all your collaboration to solve it, keep it rocking! 🎸. Leaving below the reference PRs that actually solved the issue.

- https://github.com/binbashar/terraform-aws-vpc-flowlogs/pull/15  [feature](https://github.com/binbashar/terraform-aws-vpc-flowlogs/issues?q=is%3Apr+is%3Aclosed+label%3Afeature) [minor](https://github.com/binbashar/terraform-aws-vpc-flowlogs/issues?q=is%3Apr+is%3Aclosed+label%3Aminor)
- https://github.com/binbashar/terraform-aws-vpc-flowlogs/pull/14  [feature](https://github.com/binbashar/terraform-aws-vpc-flowlogs/issues?q=is%3Apr+is%3Aclosed+label%3Afeature) [patch](https://github.com/binbashar/terraform-aws-vpc-flowlogs/issues?q=is%3Apr+is%3Aclosed+label%3Apatch)

ps. Special thanks to @diego-ojeda-binbash and @lgallard 🙏🏼 🚀 

CC: @binbashar/leverage-project-terraform-admin @binbashar/leverage-project-terraform-dev
