### ISSUE TITLE
Remove unsupported "region" attribute from s3_bucket

### ISSUE THREAD

**Issue by rafaljanicki** [binbashar/terraform-aws-vpc-flowlogs#7]
## Describe the Bug
terraform-provider-aws 3.0.0 has removed the unsupported attribute "region" from s3_bucket. As the module is using this attribute, running it results in an error "Error: "region": this field cannot be set"

## Expected Behavior
Running the module shouldn't result in the error

## Steps to Reproduce
1. Run terraform apply

## Environment (please complete the following information):

Terraform 0.12
terraform-provider-aws 3.0.0 (happens for 3.1.0 as well)

Here's a GH bug entry from terraform-provider-aws: https://github.com/terraform-providers/terraform-provider-aws/issues/14441

**Comment by exequielrafaela** [comment]
@rafaljanicki thanks for reporting this issue, it will be addressed at https://github.com/binbashar/terraform-aws-vpc-flowlogs/pull/8

CC: @binhash/leverage-ref-architecture-aws-admin
